name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Check env
        run: |
          node -e "if (!process.env.DEPLOY_TOKEN) { throw new Error('Required environment variable DEPLOY_TOKEN is not set'); }"
        env:
          CI: true

          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: node --max-old-space-size=50 test.js --ci
        env:
          NODE_OPTIONS: --max-old-space-size=4096

